version: '3.9'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - backend
    
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend

networks:
  backend:
